
version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  fraud-risk-engine:
    build: .
    image: vaibhavkadam6330/fraud-risk-engine:latest
    container_name: fraud-risk-engine
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
